FROM ubuntu:latest

# Ouch, please use a fixed version of ubuntu from docker hub!

# Add maintainer

#
# TEST FIRST:
#
# Write a test in `circle.yml`
#

##############
# Prepartion #
##############

# Add maintainer

# Install python

# Install flask

###########
# My blog #
###########

# Add app user

# Add host dir

# Define workdir

# Add entrypoint script

# Set default command

#
# DO NOT FORGET TO CHOWN STUFF
#